spring:
  datasource:
    url: jdbc:mysql://localhost:3306/brosout_db
    username: brosout_user
    password: bros0ut_pw
    driver-class-name: com.mysql.cj.jdbc.Driver

  hikari:
    maximum-pool-size: 10
    minimum-idle: 2
    idle-timeout: 300000
    max-lifetime: 18000000
    connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false

  flyway:
    locations: classpath:db/migration

jackson:
  serialization:
    indent-output: false

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info

application:
  cors:
    allowed-origin-patterns:
      - "https://app.example.com"
      - "https://admin.example.com"
    allowed-methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed-headers: ["*"]
    exposed-headers: ["Authorization", "Content-Type"]
    allow-credentials: true