spring:
  datasource:
    url: jdbc:mysql://localhost:3306/brosout_db
    username: brosout_user
    password: bros0ut_pw
    driver-class-name: com.mysql.cj.jdbc.Driver

  hikari:
    maximum-pool-size: 5
    minimum-idle: 2
    idle-timeout: 300000
    max-lifetime: 18000000
    connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

jackson:
  serialization:
    indent-output: true

logging:
  level:
    org.springframework: DEBUG